# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11mANAKdQ8TBRPiLQYOP3tRFyRTcAmq31
"""

import streamlit as st
import joblib

model = joblib.load('model1.pkl')

st.title("Aplikasi Analisis Sentimen")

text = st.text_input("Masukkan teks untuk analisis sentimen:")

if st.button("Analisis Sentimen"):
    result = model.predict([text])[0]
    st.write(f"Hasil analisis sentimen: {result}")